name: Build Docker
description: Builds a Docker image, uploads gzipped tar artifact

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .
  image-label:
    description: Image label, used as tag prefix (my-api:latest), file (my-api-image.tar,my-api-image.gz) and artifact name (my-api-image)
    required: true
  image-tag:
    description: Docker image tag, e.g. 'latest' (default) or a version number
    required: false
    default: latest
  npm-token:
    description: NPM token to fetch private packages
    required: true
  upload-artifact:
    description: |
      Whether to upload the artifact to GitHub Actions.
      Useful to disable for PR runs.
      Set to anything else than 'true' to disable.
    required: false
    default: 'true'

# Why not use the official docker GitHub actions?
# Well, they only support buildx, which only supports BuildKit, which doesn't support verifying the authenticity
# of images with Docker Content Trust https://github.com/docker/buildx/issues/987

runs:
  using: "composite"
  steps:

    - name: Build
      shell: bash
      env:
        DOCKER_BUILDKIT: '0'
        NPM_TOKEN: ${{ inputs.npm-token }}
      working-directory: ${{ inputs.working-directory }}/
      run: docker build --tag ${{ inputs.image-label }}:${{ inputs.image-tag }} --disable-content-trust=false  . --build-arg NPM_TOKEN=$NPM_TOKEN

    - name: Export
      shell: bash
      working-directory: ${{ inputs.working-directory }}/
      run: docker save --output ${{ inputs.image-label }}-docker-image.tar ${{ inputs.image-label }}:${{ inputs.image-tag }}

    - name: Compress docker image
      run: gzip ${{ inputs.image-label }}-docker-image.tar
      working-directory: ${{ inputs.working-directory }}/
      shell: bash

    - name: Upload artifact
      if: inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.image-label }}-docker-image
        path: ${{ inputs.working-directory }}/${{ inputs.image-label }}-docker-image.tar.gz
        if-no-files-found: error
