name: Build Docker
description: Builds a Docker image, uploads gzipped tar artifact

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .
  image-label:
    description: Image label, used as tag prefix (my-api:latest), file (my-api-image.tar,my-api-image.gz) and artifact name (my-api-image)
    required: true
  image-tag:
    description: Docker image tag, e.g. 'latest' (default) or a version number
    required: false
    default: latest
  npm-token:
    description: NPM token to fetch private packages
    required: false
    default: ''
  upload-artifact:
    description: |
      Whether to upload the artifact to GitHub Actions.
      Useful to disable for PR runs.
      Set to anything else than 'true' to disable.
    required: false
    default: 'true'
  use-buildkit:
    description: |
      Whether to use Docker BuildKit.
      Set to 'true' to enable.
      Note: BuildKit doesn't support verifying the authenticity
      of images with Docker Content Trust https://github.com/docker/buildx/issues/987
    required: false
    default: 'false'
  disable-content-trust:
    description: |
      Whether to disable Docker Content Trust.
      Required to use docker images that have not been signed.
      Set to 'true' to disable.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:

    - name: Set up Docker Buildx
      if: inputs.use-buildkit == 'true'
      uses: docker/setup-buildx-action@v3

    - name: Build
      shell: bash
      if: inputs.use-buildkit == 'false'
      env:
        DOCKER_BUILDKIT: '0'
        NPM_TOKEN: ${{ inputs.npm-token }}
      working-directory: ${{ inputs.working-directory }}/
      run: docker build --tag ${{ inputs.image-label }}:${{ inputs.image-tag }} --disable-content-trust=${{ inputs.disable-content-trust }}  . --build-arg NPM_TOKEN=$NPM_TOKEN

    - name: Buildx build
      shell: bash
      if: inputs.use-buildkit != 'false'
      env:
        DOCKER_BUILDKIT: '1'
        NPM_TOKEN: ${{ inputs.npm-token }}
      working-directory: ${{ inputs.working-directory }}/
      run: docker buildx build --load --tag ${{ inputs.image-label }}:${{ inputs.image-tag }} . --build-arg NPM_TOKEN=$NPM_TOKEN

    - name: Export
      shell: bash
      working-directory: ${{ inputs.working-directory }}/
      run: docker save --output ${{ inputs.image-label }}.tar ${{ inputs.image-label }}:${{ inputs.image-tag }}

    - name: Compress docker image
      run: zip ${{ inputs.image-label }}-docker-image.zip ${{ inputs.image-label }}.tar
      working-directory: ${{ inputs.working-directory }}/
      shell: bash

    - name: Upload artifact
      if: inputs.upload-artifact == 'true'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.image-label }}-docker-image
        path: ${{ inputs.working-directory }}/${{ inputs.image-label }}-docker-image.zip
        if-no-files-found: error
