name: Deploy CDK
description: Deploy CDK
inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: 24.x
  aws-access-key-id:
    description: AWS Access Key ID to authenticate with (also specify `aws-secret-access-key`)
    required: false
  aws-secret-access-key:
    description: AWS Access Key Secret to authenticate with (also specify `aws-access-key-id`)
    required: false
  aws-account-id:
    description: AWS account ID to authenticate to using GitHub federation (also specify `aws-role-name`)
    required: false
  aws-role-name:
    description: AWS role name to authenticate to using GitHub federation (also specify `aws-account-id`)
    required: false
  aws-region:
    description: AWS region to deploy to
    required: true
  infrastructure-artifact-name:
    description: Name of infrastructure artifact
    default: infrastructure
    required: false
  app-artifact-unzips:
    description: |
      One or more (lines) of colon-separated pairs, indicating A) artifact name B) destination folder where the artifact is unzipped prior to running CDK commands. E.g.:
      app-artifact-unzips: |-
        website:website/build
        app:app/dist
        poller:poller/build
    default: website:website/build
    required: false
  static-site-transforms:
    description: |
      One or more (lines) of colon-separated pairs, indicating A) placeholder variable value used in static site build B) secret value to replace placeholder value with throughout the build E.g.:
      static-site-transforms: |-
        VITE_MAKER_GRAPH_API_ENDPOINT:SECRET VALUE
        VITE_CLIENT_ID:SECRET VALUE
        VITE_TENANT_ID:SECRET VALUE
    required: false

runs:
  using: composite
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Unzip infrastructure artifact
      run: unzip -q artifacts/${{ inputs.infrastructure-artifact-name }}/${{ inputs.infrastructure-artifact-name }}.zip -d ${{ inputs.infrastructure-artifact-name }}
      shell: bash

    - name: Rebuild infrastructure node_modules
      shell: bash
      run: npm rebuild && npm run prepare --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: Unzip app artifacts
      run: |
        # Configure static site transforms if provided
        if [ ! -z "${{ inputs.static-site-transforms }}" ]
        then
          readarray -t transforms <<<"${{ inputs.static-site-transforms }}"
          replacements=""
          for i in "${!transforms[@]}"
          do
            trimmed="$(echo -e "${transforms[i]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            IFS=':' read -r placeholder value <<< "$trimmed"
            if [ ! -z "$placeholder" ]
            then
              replacements+="s/{{$placeholder}}/$(echo $value | sed -e 's/\\/\\\\/g; s/\//\\\//g; s/&/\\\&/g')/gI;"
            fi
          done
        fi
        if [ ! -z "${{ inputs.app-artifact-unzips }}" ]
        then
          # Extract app artifacts
          readarray -t lines <<<"${{ inputs.app-artifact-unzips }}"
          for i in "${!lines[@]}"
          do
            trimmed="$(echo -e "${lines[i]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            IFS=':' read -ra pair <<< "$trimmed"
            mkdir -p "${pair[1]}"
            unzip -q "artifacts/${pair[0]}/${pair[0]}.zip" -d "${pair[1]}"
  
            # Apply static site transforms if provided 
            if [ ! -z "$replacements" ]
            then
              find "${pair[1]}" -type f \( -name '*.js' -o -name '*.html' \) -exec sed -i "$replacements" {} \;
            fi
          done
        fi
      shell: bash

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Configure AWS Credentials (access key)
      if: ${{ inputs.aws-access-key-id && inputs.aws-secret-access-key }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Configure AWS Credentials (GitHub federation)
      if: ${{ inputs.aws-account-id && inputs.aws-role-name }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/${{ inputs.aws-role-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: CDK bootstrap
      shell: bash
      run: npm run bootstrap
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: CDK diff
      shell: bash
      run: npm run diff
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: CDK deploy secrets
      shell: bash
      run: npm run deploy-secrets --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: Set secrets (secrets)
      shell: bash
      run: |
        if [[ $(jq '.scripts["deploy-secrets"]' < package.json;) != null ]]; then
          npm run set-secrets --if-present
        fi
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: CDK deploy
      shell: bash
      run: npm run deploy --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: CDK deploy infra
      shell: bash
      run: npm run deploy-infra --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: Set secrets (infra)
      shell: bash
      run: npm run set-secrets --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: Run DB Migrations
      shell: bash
      run: npm run invoke-migrate-db --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: CDK deploy app
      shell: bash
      run: npm run deploy-app --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}

    - name: Set secrets (app)
      shell: bash
      run: npm run set-secrets --if-present
      working-directory: ${{ inputs.infrastructure-artifact-name }}
