name: Build Node zip
description: Build Node app and upload zip artifact

inputs:
  node-version:
    description: Node version
    required: false
    default: 24.x
  working-directory:
    description: Working directory
    required: false
    default: '.'
  build-path:
    description: Build output path
    required: false
    default: build
  artifact-name:
    description: Artifact name
    required: false
    default: node-app
  static-site:
    required: false
    default: false
  static-site-env-prefix:
    required: false
    default: VITE
  npm-auth-token:
    description: NPM auth token (optional)
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    # setup node + private repo access
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://npm.pkg.github.com'
        scope: '@makerxstudio'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    # prepare static sites for config transformation upon later deployment
    - if: ${{ inputs.static-site }}
      run: sed -n 's/\(${{ inputs.static-site-env-prefix }}_[A-Z0-9_]\+\)=\(.*\)/\1={{\1}}/p' .env.sample > .env && cat .env
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      
    # run npm ci preventing script access to npm auth token
    - run: npm ci --ignore-scripts
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

    # allow scripts to run without npm auth token
    - run: npm rebuild && npm run prepare --if-present
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Prepare
      run: npm run prepare --if-present
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Build
      run: npm run build
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      # CDK infrastructure build calls npm ci on /infrastructure/build, which may fail without NODE_AUTH_TOKEN
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-auth-token }}

    - name: Zip build folder
      run: pushd ${{ inputs.build-path }}; zip -q -r ../${{ inputs.artifact-name }}.zip *
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.working-directory }}/${{ inputs.artifact-name }}.zip
        if-no-files-found: error
