name: Solve zendesk ticket when the issue is closed
on:
  issues:
    types: [closed]
jobs:
  issue_closed:
    uses: makerxstudio/shared-config/.github/workflows/github_zendesk_issue_closed.yml@main
    with:
      ZENDESK_TENANT_NAME: ${{ vars.ZENDESK_TENANT_NAME }}
    secrets:
      ZENDESK_BASIC_AUTH: ${{ secrets.ZENDESK_BASIC_AUTH }}
