name: Create Zendesk ticket when an issue is labelled with makerx 
on:
  issues:
    types: [labeled]
jobs:
  issue_created:
    uses: makerxstudio/shared-config/.github/workflows/github_zendesk_issue_labelled.yml@main
    with:
      ZENDESK_TENANT_NAME: ${{ vars.ZENDESK_TENANT_NAME }}
      ISSUE_LABEL: ${{ vars.ZENDESK_ISSUE_LABEL }}
    secrets:
      ZENDESK_AUTH_TOKEN: ${{ secrets.ZENDESK_AUTH_TOKEN }}
