name: Add comment to zendesk ticket on GitHub issue commented
on:
  issue_comment:
    types: [created]
jobs:
  issue_closed:
    uses: makerxstudio/shared-config/.github/workflows/github_zendesk_issue_commented.yml@main
    with:
      ZENDESK_TENANT_NAME: ${{ vars.ZENDESK_TENANT_NAME }}
    secrets:
      ZENDESK_AUTH_TOKEN: ${{ secrets.ZENDESK_AUTH_TOKEN }}