name: Solve zendesk ticket when the issue is closed
on:
  issues:
    types: [closed]
jobs:
  issue_closed:
    uses: makerxstudio/shared-config/.github/workflows/github_zendesk_issue_closed.yml@main
    with:
      ZENDESK_TENANT_NAME: ${{ vars.ZENDESK_TENANT_NAME }}
      ISSUE_LABEL: ${{ vars.ZENDESK_ISSUE_LABEL }}
    secrets:
      ZENDESK_AUTH_TOKEN: ${{ secrets.ZENDESK_AUTH_TOKEN }}
