name: Solve Zendesk ticket
on:
  workflow_call:
    inputs:
      ZENDESK_TENANT_NAME:
        description: 'The zendesk tenant name, can be found in the URL, for example https://my-subdomain.zendesk.com/'
        required: true
        type: string
      ISSUE_LABEL:
        description: 'The required label to trigger this workflow'
        required: true
        type: string
    secrets:
      ZENDESK_AUTH_TOKEN:
        description: 'The zendesk basic auth token for authentification. See https://support.zendesk.com/hc/en-us/articles/115000510267-How-can-I-authenticate-API-requests-#heading2'
        required: true
jobs:
  solve-ticket:
    name: Solve Zendesk ticket
    if: ${{ contains(github.event.issue.labels.*.name, inputs.ISSUE_LABEL) }}
    runs-on: ubuntu-latest
    steps:
      - env:
          TENANT_NAME: ${{ inputs.ZENDESK_TENANT_NAME }}
          ZENDESK_AUTH_TOKEN: ${{ secrets.ZENDESK_AUTH_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          ## look up ticket in zendesk
          echo "Looking up ticket by issue: $ISSUE_URL"
          tickets=$(curl --silent "https://$TENANT_NAME.zendesk.com/api/v2/search.json?query=external_id:$ISSUE_URL" -H "Authorization: Basic $ZENDESK_AUTH_TOKEN" -H "Content-Type: application/json")
          ticket_number=$(echo $tickets | jq '.results[0].id')
          echo "Found ticket number: " $ticket_number

          if [[ "$ticket_number" == "null" ]];
          then
            echo "Skip, Zendesk ticket not found"
          else
            ## Set zendesk ticket to solved
            curl -X PUT https://$TENANT_NAME.zendesk.com/api/v2/tickets/$ticket_number -H "Authorization: Basic $ZENDESK_AUTH_TOKEN" -H "Content-Type: application/json" --data-binary @- <<DATA
            {
              "ticket": {
                "comment": { "body": "[GITHUB_ISSUE_COMMENT]\n\nClosed in GitHub" },
                "status": "solved"
              }
            }
          DATA
          fi
