on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 16.x
      working-directory:
        required: false
        type: string
        default: '.'
      build-path:
        required: false
        type: string
        default: build
      artifact-name:
        required: false
        type: string
        default: node-app
    secrets:
      npm-auth-token:
        description: NPM auth token (optional, GITHUB_TOKEN is used by default)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: ./github/actions/node-build
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          build-path: ${{ inputs.build-path }}
          artifact-name: ${{ inputs.artifact-name }}
          npm-auth-token: ${{ secrets.npm-auth-token || secrets.GITHUB_TOKEN }}
