on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: '.'
      lint-script:
        required: false
        type: string
        default: npm run lint --if-present
      compile-script:
        required: false
        type: string
        default: npm run check-types --if-present
      test-script:
        required: false
        type: string
        default: npm run test --if-present
      audit-script:
        required: false
        type: string
        default: npm audit
      build-script:
        required: false
        type: string
        default: npm run build
      run-build:
        required: false
        type: boolean
        default: false

defaults:
  run:
    shell: bash
    working-directory: ${{ inputs.working-directory }}

jobs:
  node-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup node + private repo access
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@makerxstudio'
          cache: 'npm'

      # run npm ci preventing script access to npm auth token
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # allow scripts to run without npm auth token
      - run: npm rebuild && npm run prepare --if-present

      # run all the CI scripts
      - run: ${{ inputs.lint-script }}
      - run: ${{ inputs.compile-script }}
      - run: ${{ inputs.test-script }}
      - run: ${{ inputs.audit-script }}
      - if: ${{ inputs.run-build }}
        run: ${{ inputs.build-script }}

      
