on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 16.x
      working-directory:
        required: false
        type: string
        default: '.'
      lint-script:
        required: false
        type: string
        default: npm run lint --if-present
      compile-script:
        required: false
        type: string
        default: npm run check-types --if-present
      run-pre-test:
        required: false
        type: boolean
        default: false
      pre-test-script:
        required: false
        type: string
      test-script:
        required: false
        type: string
        default: npm run test --if-present
      audit-script:
        required: false
        type: string
        default: npm audit
      build-script:
        required: false
        type: string
        default: npm run build
      run-build:
        required: false
        type: boolean
        default: false
      run-commit-lint:
        required: false
        type: boolean
        default: false
      commit-lint-script:
        required: false
        type: string
        default: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
    secrets:
      npm-auth-token:
        description: NPM auth token (don't pass in on a PR build on a public repository)
        required: false

jobs:
  node-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # setup node + private repo access
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@makerxstudio'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      # run npm ci preventing script access to npm auth token
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token || secrets.GITHUB_TOKEN }}
      # allow scripts to run without npm auth token
      - run: npm rebuild && npm run prepare --if-present

      # run all the CI scripts
      - name: 'Commit lint'
        if: ${{ inputs.run-commit-lint }}
        run: ${{ inputs.commit-lint-script }}
      - name: Lint
        run: ${{ inputs.lint-script }}
      - name: Compile
        run: ${{ inputs.compile-script }}
      - name: Pre-test
        if: ${{ inputs.run-pre-test }}
        run: ${{ inputs.pre-test-script }}
      - name: Test
        run: ${{ inputs.test-script }}
      - name: Audit
        run: ${{ inputs.audit-script }}
      - name: Build
        if: ${{ inputs.run-build }}
        run: ${{ inputs.build-script }}
        # CDK infrastructure build calls npm ci on /infrastructure/build, which may fail without NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token || secrets.GITHUB_TOKEN }}
          

