name: deploy-web-app
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 16.x
      web-app-name:
        required: true
        type: string
      artifact-name:
        required: false
        type: string
        default: node-app
      artifact-file-name:
        required: false
        type: string
        default: 'node-app.zip'
      environment-name:
        required: false
        default: 'Development'
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

env:
  AZURE_WEBAPP_NAME: ${{ inputs.web-app-name }}
  NODE_VERSION: ${{ inputs.node-version }}

jobs:
  deploy-azure-web-app:
    name: ${{ inputs.environment-name }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ inputs.artifact-file-name }}
