name: deploy-web-app
on:
  workflow_call:
    inputs:
      nodeVersion:
        required: false
        type: string
        default: 16.x
      webAppName:
        required: true
        type: string
      artifactName:
        required: false
        type: string
        default: 'node-app'
      artifactFileName:
        required: false
        type: string
        default: 'node-app.zip'
      environmentName:
        required: false
        default: 'Development'
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

env:
  AZURE_WEBAPP_NAME: ${{ inputs.webAppName }}
  NODE_VERSION: ${{ inputs.nodeVersion }}

jobs:
  deploy-azure-web-app:
    name: ${{ inputs.environmentName }}
    permissions:
      contents: none
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environmentName }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ inputs.artifactFileName }}
