on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 24.x
      working-directory:
        required: false
        type: string
        default: '.'
      build-path:
        required: false
        type: string
        default: build
      artifact-name:
        required: false
        type: string
        default: node-app
      pre-run-script:
        required: false
        type: string
    secrets:
      npm-auth-token:
        description: NPM auth token (optional, GITHUB_TOKEN is used by default)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      # setup node + private repo access
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@makerxstudio'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Pre-run
        if: ${{ inputs.pre-run-script }}
        run: ${{ inputs.pre-run-script }}
        
      # run npm ci preventing script access to npm auth token
      - run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token || secrets.GITHUB_TOKEN }}
      # allow scripts to run without npm auth token
      - run: npm rebuild && npm run prepare --if-present

      - name: Prepare
        run: npm run prepare --if-present

      - name: Build
        run: npm run build
        # CDK infrastructure build calls npm ci on /infrastructure/build, which may fail without NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token || secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/${{ inputs.build-path }}
          if-no-files-found: error
