on:
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Test Report
        path: 'test-results.xml'
        reporter: jest-junit